# -*- coding: utf-8 -*-
"""Aula de Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xI8lxtwsE-Ak21trz-0600B8eg3ExkXv
"""



"""Python com analise de dados (Pandas)"""



from IPython.core.interactiveshell import error
#importando bibli pandas ao importar estamos colocando o apelido da biblioteca como pd 
import pandas as pd
#DF e igual ao excel data frame
#comando sep ; para separar as mesmas

df = pd.read_csv("/content/drive/MyDrive/Dio/Curso Dio Python BH/datasets/Gapminder.csv",error_bad_lines=False,sep=";")

df.head(5)#mostra as 5 primeiras linhas do arquivo csv

#Renomeando as columas para nomes em pt-br antes disso incluir que a variavel df recebe essa nova modificacao 
df = df.rename(columns={"country":"Pais","continent":"Continente","year":"Ano", "lifeExp":"Expectativa de vida", "pop":"População", "gdpPercap":"PIB"})



df.head(10) # relendo e vendo as primeiras  10 linhas

#para saber o total de linhas e colunas do arquivo cvs
df.shape

#para saber os nomes das colunas 
df.columns

df.dtypes #mostra os tipos de dados

df.tail() # mostra as ultimas linhas do conjunto de dados se quiser pode pesquisar um numero especifico de linhas

df.describe()#retorna estatisticas da tabela media , media,quartis  etc.

df["Continente"].unique()#procura por algo especifico nesse caso continente nan significa valor nulo na planilha

Oceania =df.loc[df["Continente"] == "Oceania"] #faz um filtro de acordo com suas buscas nesse caso oceania
#df.loc e para localizar 
Oceania.head()

#agrupamento de dados ,por continente , trazendo quantos paises por continente .
df.groupby("Continente")["Pais"].nunique()

#saber para cada ano  qual a expectativa de vida media 

df.groupby("Ano")["Expectativa de vida"].mean()

df["PIB"].mean() #Retorna media do pib

df["PIB"].sum()#retorna soma do pib