# -*- coding: utf-8 -*-
"""Python_Dio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pUWm9eWsLMdzju89kWBGQzuG8qmMxTEb
"""

from io import StringIO
print ('hello world')
print(1+15+8990)
print(1.5+1.45)
print('1'+'12')

age = 23
name = 'TestName'
print(f'meu nome é {name } e eu tenho {age} anos de idade')

nome = "teste2"
idade = 20

print(nome,idade)

nome , idade = 'teste3' , 19 
print (nome ,idade )

Preco = 10.50

idade = 20 

produto = 10
produto1 = 20


print ( produto + produto1)
print ( produto - produto1)
print ( produto * produto1)
print ( produto / produto1)
print ( produto % produto1)
print ( produto ** produto1 )

x = ( 10 + 5 ) * 4
y = 10 / 2 + 25 * 2

print ( x + y)

print ('--------------------------------------------------------')

saldo = 450 
saque = 200 

print (saldo == saque)

print (saldo != saque)

print (saldo > saque)

print (saldo < saque)

print ('--------------------------------------------------------')


saldo = 510 
saque = 200
limite = 400

a= saldo >= saque and saque <= limite

print (a)

a= saldo >= saque or saque <= limite

print (a)

a=  not(saldo >= saque) and saque <= limite

print (a)

print ('--------------------------------------------------------')


# operadores de associacao  atentar que os nomes de comparacao para in tem que estar identico ao procurado , inclusive ver acento e maiusculas  ou minusculas
curso = "curso de python " 
frutas = [' laranja ', 'uva ', 'limao']
saques = [1500,100 ]

print ('python' in curso)
print ('maca' not in frutas)
print (200 in saques)